basePath: /
definitions:
  BidHandlers.CreateBidRequest:
    properties:
      creatorUsername:
        type: string
      description:
        type: string
      name:
        type: string
      organizationId:
        type: string
      status:
        type: string
      tenderId:
        type: string
    type: object
  BidHandlers.UpdateBidRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  TenderHandlers.UpdateTenderRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  models.Bid:
    description: Предложение для тендера
    properties:
      created_at:
        type: string
      created_by:
        description: ID пользователя
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/models.BidStatus'
      tender_id:
        type: string
      updated_at:
        type: string
      version:
        type: integer
    type: object
  models.BidStatus:
    enum:
    - CREATED
    - PUBLISHED
    - CANCELED
    type: string
    x-enum-varnames:
    - BidCreated
    - BidPublished
    - BidCanceled
  models.Tender:
    description: Tender содержит информацию о тендере
    properties:
      created_at:
        type: string
      created_by:
        description: ID пользователя
        type: string
      creator_username:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      organization_id:
        type: string
      status:
        $ref: '#/definitions/models.TenderStatus'
      tender_version:
        $ref: '#/definitions/models.TenderVersion'
      updated_at:
        type: string
      version:
        type: integer
    type: object
  models.TenderStatus:
    description: TenderStatus содержит возможные статусы тендера
    enum:
    - CREATED
    - PUBLISHED
    - CLOSED
    type: string
    x-enum-varnames:
    - TenderCreated
    - TenderPublished
    - TenderClosed
  models.TenderVersion:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      tender_id:
        type: string
      version:
        type: integer
    type: object
host: cnrprod1725725290-team-77871-32639.avito2024.codenrock.com
info:
  contact: {}
  description: API Server for TodoList Application
  title: TenderAPI
  version: "1.0"
paths:
  /api/bids/{bidId}/edit:
    patch:
      consumes:
      - application/json
      description: Обновляет параметры предложения и возвращает обновленные данные
        предложения.
      parameters:
      - description: ID предложения
        format: uuid
        in: path
        name: bidId
        required: true
        type: string
      - description: Тело запроса для обновления предложения
        in: body
        name: bid
        required: true
        schema:
          $ref: '#/definitions/BidHandlers.UpdateBidRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное обновление предложения
          schema:
            $ref: '#/definitions/models.Bid'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Предложение не найдено
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление существующего предложения
      tags:
      - Bids
  /api/bids/{bidId}/rollback/{version}:
    put:
      consumes:
      - application/json
      description: Откатывает предложение к указанной версии и возвращает обновленные
        данные предложения.
      parameters:
      - description: ID предложения
        format: uuid
        in: path
        name: bidId
        required: true
        type: string
      - description: Версия предложения
        in: path
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Обновленные данные предложения
          schema:
            $ref: '#/definitions/models.Bid'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Предложение или версия не найдены
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Откат предложения к указанной версии
      tags:
      - Bids
  /api/bids/{tenderId}/list:
    get:
      consumes:
      - application/json
      description: Возвращает список предложений, связанных с указанным тендером.
      parameters:
      - description: ID тендера
        format: uuid
        in: path
        name: tenderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список предложений для тендера
          schema:
            items:
              $ref: '#/definitions/models.Bid'
            type: array
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение списка предложений для указанного тендера
      tags:
      - Bids
  /api/bids/my:
    get:
      consumes:
      - application/json
      description: Возвращает список предложений текущего пользователя по его имени
        пользователя.
      parameters:
      - description: Имя пользователя
        format: string
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список предложений пользователя
          schema:
            items:
              $ref: '#/definitions/models.Bid'
            type: array
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение списка предложений текущего пользователя
      tags:
      - Bids
  /api/bids/new:
    post:
      consumes:
      - application/json
      description: Создает новое предложение для существующего тендера
      parameters:
      - description: Данные для создания нового предложения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/BidHandlers.CreateBidRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание предложения
          schema:
            $ref: '#/definitions/models.Bid'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание нового предложения
      tags:
      - Bids
  /api/ping:
    get:
      consumes:
      - application/json
      description: Возвращает "ok" с кодом состояния 200
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      tags:
      - Health
  /api/tenders:
    get:
      consumes:
      - application/json
      description: Возвращает список всех тендеров из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tender'
            type: array
        "500":
          description: Error fetching data
          schema:
            type: string
      summary: Получение списка тендеров
      tags:
      - Tenders
  /api/tenders/{tenderId}/edit:
    patch:
      consumes:
      - application/json
      description: Обновляет параметры существующего тендера и возвращает обновленный
        тендер
      parameters:
      - description: ID тендера
        in: path
        name: tenderId
        required: true
        type: string
      - description: Тело запроса для обновления тендера
        in: body
        name: tender
        required: true
        schema:
          $ref: '#/definitions/TenderHandlers.UpdateTenderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное обновление тендера
          schema:
            $ref: '#/definitions/models.Tender'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Тендер не найден
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление существующего тендера
      tags:
      - Tenders
  /api/tenders/{tenderId}/rollback/{version}:
    put:
      description: Откатывает параметры тендера к указанной версии
      parameters:
      - description: ID тендера
        in: path
        name: tenderId
        required: true
        type: string
      - description: Версия тендера
        in: path
        name: version
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный откат тендера
          schema:
            $ref: '#/definitions/models.Tender'
        "400":
          description: Неверный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Тендер или версия не найдены
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Откат тендера
      tags:
      - Tenders
  /api/tenders/new:
    post:
      consumes:
      - application/json
      description: Создает новый тендер и возвращает его
      parameters:
      - description: Тело запроса для создания тендера
        in: body
        name: tender
        required: true
        schema:
          $ref: '#/definitions/models.Tender'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание тендера
          schema:
            $ref: '#/definitions/models.Tender'
      summary: Создание нового тендера
      tags:
      - Tenders
swagger: "2.0"
