basePath: /
definitions:
  models.Tender:
    description: Tender содержит информацию о тендере
    properties:
      created_at:
        type: string
      created_by:
        description: ID пользователя
        type: string
      creator_username:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      organization_id:
        type: string
      status:
        $ref: '#/definitions/models.TenderStatus'
      updated_at:
        type: string
      version:
        type: integer
    type: object
  models.TenderStatus:
    description: TenderStatus содержит возможные статусы тендера
    enum:
    - CREATED
    - PUBLISHED
    - CLOSED
    type: string
    x-enum-varnames:
    - TenderCreated
    - TenderPublished
    - TenderClosed
host: localhost:8080
info:
  contact: {}
  description: API Server for TodoList Application
  title: TenderAPI
  version: "1.0"
paths:
  /api/ping:
    get:
      consumes:
      - application/json
      description: Возвращает "ok" с кодом состояния 200
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      tags:
      - Health
  /api/tenders:
    get:
      consumes:
      - application/json
      description: Возвращает список всех тендеров из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tender'
            type: array
        "500":
          description: Error fetching data
          schema:
            type: string
      summary: Получение списка тендеров
      tags:
      - Tenders
  /api/tenders/new:
    post:
      consumes:
      - application/json
      description: Создает новый тендер и возвращает его
      parameters:
      - description: Тело запроса для создания тендера
        in: body
        name: tender
        required: true
        schema:
          $ref: '#/definitions/models.Tender'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание тендера
          schema:
            $ref: '#/definitions/models.Tender'
      summary: Создание нового тендера
      tags:
      - Tenders
swagger: "2.0"
